import "./globals.css";
import { Navbar } from "@/src/components/Navbar";
import { RoutingNavLayout } from "@/src/components/Navbar/Routes";
import ErrorBoundary from "@/src/components/ErrorBoundary";

export const metadata = {
  title: "sci-teck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <Navbar />
          <RoutingNavLayout />
          {children}
      </body>
    </html>
  );
}
