import "./globals.css";
import type { Metadata } from "next";
import { Navbar } from "@/src/components/Navbar";
import { RoutingNavLayout } from "@/src/components/Navbar/Routes";

import { ModalProvider } from "../providers/ModalProvider";
import { AuthProvider } from "../providers/AuthProvider";
import { WebSocketProvider } from "../providers/WebSocketProvider";
import { WebRTCProvider } from "../providers/WebRTCProvider";

export const metadata: Metadata = {
  title: "Sci-Tech City",
  themeColor: { color: 'red'},
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ModalProvider>
            <WebSocketProvider>
              <WebRTCProvider>
                <Navbar />
                <RoutingNavLayout />
                {children}
              </WebRTCProvider>
            </WebSocketProvider>
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
